### ISSUE TITLE
请问开源这东西图啥？想让国服早点死？

### ISSUE THREAD

**Issue by Norca0721** [Natsunokonoha/NaTsuTool#1]
想让国服早点停止运营可以给sega发邮箱，要不这样，你背上炸药包去把华立总部炸了吧

**Comment by Natsunokonoha** [comment]
就是看不惯闲鱼？至于像要国服死我不敢苟同，毕竟很多bot都能实现本项目许多东西呢～，而且我没有提供任何姓名对应uid的api，相对来说也不存在影响其他用户，至于用户是怎么拿到别人的userid那是用户的事。但是你说得对我应该去掉aeskey和偏移的

**Comment by Natsunokonoha** [comment]
相应api删掉咯
