### ISSUE TITLE
有点忍俊不禁了

### ISSUE THREAD

**Issue by nuym** [Natsunokonoha/NaTsuTool#2]
# 先不提你这玩意开源对不对，看看你代码规范程度。
- 包名大写
- 没有包名
- 逻辑杂乱
- 变量名命名不规范
- 诸多问题不一一阐述
# 不知道你开源的目的在哪
暴力解小黑屋本身就是对舞萌服务器的一种网络攻击，解了自己的小黑屋，让别人受网络影响，不知道你此处的目的。写科技开源甚至还把加密的盐值，狗号都带上，挺逆天的。

**Comment by Natsunokonoha** [comment]
删了删了小团体别视奸了😭

**Comment by Natsunokonoha** [comment]
删了删了小团体别视奸我了😭
